app = "student-processing-backend"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["paketo-buildpacks/java"]

[env]
  PORT = "8080"
  JAVA_OPTS = "-Xmx400m -XX:MaxMetaspaceSize=80m -XX:ReservedCodeCacheSize=24m -Xss256k -XX:+UseG1GC -XX:+UseStringDeduplication"
  BPL_JVM_THREAD_COUNT = "30"
  BPL_JVM_HEAD_ROOM = "5"
  H2_CONSOLE_ENABLED = "false"
  SHOW_SQL = "false"
  SPRING_PROFILES_ACTIVE = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"